"use client";

import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { ChevronDown, Sparkles, MessageCircleQuestion } from "lucide-react";
import { cn } from "@/lib/utils";

interface FAQItem {
  question: string;
  answer: string;
  category: string;
}

const faqs: FAQItem[] = [
  {
    category: "General",
    question: "What is NextCareer AI?",
    answer: "NextCareer AI is an AI-powered platform designed to help job seekers create ATS-friendly resumes, analyze their existing resumes, and generate personalized career roadmaps. Our suite of tools uses advanced AI to optimize your job search and accelerate your career growth."
  },
  {
    category: "General",
    question: "Is NextCareer AI free to use?",
    answer: "Yes! We offer a generous free tier that includes access to our Resume Builder, Resume Analyzer, and Career Roadmap generator. You can create, analyze, and download professional resumes without any cost."
  },
  {
    category: "Resume Builder",
    question: "What makes your resume builder different?",
    answer: "Our Resume Builder uses AI to help you craft compelling content, suggests improvements in real-time, and ensures your resume is optimized for Applicant Tracking Systems (ATS). We offer 20+ professional templates, all designed to pass ATS scans while looking great to human recruiters."
  },
  {
    category: "Resume Builder",
    question: "Can I upload my existing resume?",
    answer: "Absolutely! You can upload your existing resume in PDF or DOCX format, and our AI will parse the content automatically. You can then edit, enhance, and format it using our builder with AI suggestions."
  },
  {
    category: "Resume Builder",
    question: "What file formats can I export my resume in?",
    answer: "You can export your resume as a PDF, which is the industry standard format preferred by most employers and ATS systems. The PDF maintains perfect formatting across all devices and platforms."
  },
  {
    category: "Resume Analyzer",
    question: "How does the Resume Analyzer work?",
    answer: "Upload your resume (PDF or DOCX), and our AI analyzes it against ATS requirements, industry best practices, and recruiter preferences. You'll receive a comprehensive score, keyword analysis, formatting feedback, and specific recommendations to improve your resume."
  },
  {
    category: "Resume Analyzer",
    question: "What is an ATS score?",
    answer: "An ATS (Applicant Tracking System) score measures how well your resume will perform when scanned by automated systems that many companies use to filter applications. A higher score means better chances of your resume reaching human recruiters. We analyze factors like keyword optimization, formatting, structure, and readability."
  },
  {
    category: "Resume Analyzer",
    question: "Is my resume data secure?",
    answer: "Yes, absolutely. We take data security seriously. Your resume is encrypted during upload and processing, and we never share your personal information with third parties. You have full control over your data and can delete it anytime."
  },
  {
    category: "Career Roadmaps",
    question: "What is a Career Roadmap?",
    answer: "A Career Roadmap is a personalized learning and development plan generated by our AI. Based on your current role, target position, and skill level, we create a step-by-step guide with recommended skills to learn, certifications to pursue, and milestones to achieve your career goals."
  },
  {
    category: "Career Roadmaps",
    question: "How personalized are the roadmaps?",
    answer: "Very personalized! Our AI considers your current experience, education, target role, industry, and timeline to create a custom roadmap. Each roadmap includes specific skills, learning resources, estimated timelines, and priority recommendations tailored to your unique career path."
  },
  {
    category: "Career Roadmaps",
    question: "Can I update my roadmap as I progress?",
    answer: "Yes! Your Career Roadmap is a living document. As you complete milestones and learn new skills, you can update your progress and the AI will adjust recommendations accordingly. This keeps your career plan relevant and achievable."
  },
  {
    category: "Templates",
    question: "How many resume templates do you offer?",
    answer: "We offer 20+ professionally designed resume templates, all optimized for ATS compatibility. Our templates cover various industries and career levels, from entry-level to executive positions. Each template is carefully crafted to balance visual appeal with ATS-friendliness."
  },
  {
    category: "Templates",
    question: "Are your templates ATS-friendly?",
    answer: "Yes! All our templates are specifically designed to pass ATS scans. We avoid complex formatting, graphics, and layouts that confuse automated systems, while maintaining a professional and modern appearance that impresses human recruiters."
  },
  {
    category: "AI Features",
    question: "How does the AI enhancement work?",
    answer: "Our AI analyzes your resume content and suggests improvements for bullet points, summaries, and descriptions. It helps you use stronger action verbs, quantify achievements, optimize keywords, and craft compelling narratives that showcase your value to employers."
  },
  {
    category: "AI Features",
    question: "Can the AI write my entire resume?",
    answer: "The AI assists and enhances your content, but it works best when you provide the foundation. You input your experience, and the AI helps polish it, suggest better phrasing, add missing keywords, and ensure everything is optimized. This approach ensures authenticity while leveraging AI's optimization capabilities."
  },
  {
    category: "Technical",
    question: "Which file formats do you support for upload?",
    answer: "We currently support PDF and DOCX (Microsoft Word) formats for resume uploads. These are the most common formats and allow our AI to accurately extract and analyze your content."
  },
  {
    category: "Technical",
    question: "What's the maximum file size for uploads?",
    answer: "The maximum file size for resume uploads is 5MB, which is more than sufficient for even the most detailed resumes with complex formatting."
  },
  {
    category: "Account & Privacy",
    question: "Do I need to create an account?",
    answer: "For basic features like the Resume Analyzer, you don't need an account. However, creating a free account allows you to save your resumes, track your progress, access your career roadmaps, and sync your data across devices."
  },
  {
    category: "Account & Privacy",
    question: "How do you protect my personal information?",
    answer: "We use industry-standard encryption for data transmission and storage. Your personal information is never sold or shared with third parties. We comply with GDPR and other privacy regulations, and you have full control to export or delete your data at any time."
  },
  {
    category: "Support",
    question: "How can I get help if I'm stuck?",
    answer: "We offer multiple support channels: you can reach out through our contact form, check our comprehensive documentation, or email our support team. We typically respond within 24 hours during business days."
  },
  {
    category: "Support",
    question: "Do you offer customer support?",
    answer: "Yes! Our support team is here to help. Whether you have technical issues, questions about features, or need guidance on optimizing your resume, we're ready to assist. Free users get email support, while premium users get priority assistance."
  }
];

const categories = Array.from(new Set(faqs.map(faq => faq.category)));

function FAQAccordion({ faq, isOpen, onToggle }: { faq: FAQItem; isOpen: boolean; onToggle: () => void }) {
  return (
    <div className="tile overflow-hidden">
      <button
        onClick={onToggle}
        className="w-full px-6 py-5 flex items-start justify-between gap-4 text-left transition-colors hover:bg-cream/30"
      >
        <span className="font-serif text-lg font-semibold text-ink pr-4">{faq.question}</span>
        <ChevronDown 
          className={cn(
            "w-5 h-5 text-indigo flex-shrink-0 transition-transform duration-300 mt-1",
            isOpen && "rotate-180"
          )} 
        />
      </button>
      <AnimatePresence initial={false}>
        {isOpen && (
          <motion.div
            initial={{ height: 0, opacity: 0 }}
            animate={{ height: "auto", opacity: 1 }}
            exit={{ height: 0, opacity: 0 }}
            transition={{ duration: 0.3, ease: [0.22, 1, 0.36, 1] }}
            className="overflow-hidden"
          >
            <div className="px-6 pb-5 pt-2">
              <p className="text-muted-foreground leading-relaxed">{faq.answer}</p>
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}

export default function FAQPage() {
  const [openIndex, setOpenIndex] = useState<number | null>(0);
  const [selectedCategory, setSelectedCategory] = useState<string>("All");

  const filteredFaqs = selectedCategory === "All" 
    ? faqs 
    : faqs.filter(faq => faq.category === selectedCategory);

  return (
    <div className="relative min-h-screen overflow-hidden">
      <div className="mx-auto max-w-5xl px-4 sm:px-6 lg:px-8 py-20 lg:py-32">
        
        {/* Header */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6 }}
          className="text-center mb-16"
        >
          {/* Badge */}
          <motion.div
            initial={{ opacity: 0, scale: 0.9 }}
            animate={{ opacity: 1, scale: 1 }}
            transition={{ duration: 0.5 }}
            className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-indigo/10 border border-indigo/20 mb-6"
          >
            <MessageCircleQuestion className="w-4 h-4 text-indigo" />
            <span className="text-sm font-medium text-indigo">Frequently Asked Questions</span>
          </motion.div>

          <motion.h1
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6, delay: 0.1 }}
            className="text-5xl sm:text-6xl lg:text-7xl font-serif font-bold tracking-tight text-ink leading-[1.1] mb-6"
          >
            Got questions?
            <br />
            <span className="text-indigo">We&apos;ve got answers</span>
          </motion.h1>

          <motion.p
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6, delay: 0.2 }}
            className="text-lg sm:text-xl text-muted-foreground max-w-2xl mx-auto"
          >
            Everything you need to know about NextCareer AI and how our AI-powered tools can help accelerate your career.
          </motion.p>
        </motion.div>

        {/* Category Filter */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6, delay: 0.3 }}
          className="flex flex-wrap justify-center gap-3 mb-12"
        >
          <button
            onClick={() => setSelectedCategory("All")}
            className={cn(
              "px-5 py-2.5 rounded-full font-medium text-sm transition-all duration-200",
              selectedCategory === "All"
                ? "bg-indigo text-white shadow-soft"
                : "bg-paper/70 text-muted-foreground border border-border hover:bg-cream/50 hover:text-ink"
            )}
          >
            All
          </button>
          {categories.map((category) => (
            <button
              key={category}
              onClick={() => setSelectedCategory(category)}
              className={cn(
                "px-5 py-2.5 rounded-full font-medium text-sm transition-all duration-200",
                selectedCategory === category
                  ? "bg-indigo text-white shadow-soft"
                  : "bg-paper/70 text-muted-foreground border border-border hover:bg-cream/50 hover:text-ink"
              )}
            >
              {category}
            </button>
          ))}
        </motion.div>

        {/* FAQ List */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6, delay: 0.4 }}
          className="space-y-4"
        >
          {filteredFaqs.map((faq, index) => (
            <motion.div
              key={`${faq.question}-${index}`}
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.4, delay: 0.05 * index }}
            >
              <FAQAccordion
                faq={faq}
                isOpen={openIndex === index}
                onToggle={() => setOpenIndex(openIndex === index ? null : index)}
              />
            </motion.div>
          ))}
        </motion.div>

        {/* Still have questions CTA */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6, delay: 0.6 }}
          className="mt-20 text-center"
        >
          <div className="tile p-12 max-w-3xl mx-auto">
            <Sparkles className="w-12 h-12 text-indigo mx-auto mb-4" />
            <h2 className="text-3xl font-serif font-bold text-ink mb-4">
              Still have questions?
            </h2>
            <p className="text-muted-foreground mb-6 max-w-xl mx-auto">
              Can&apos;t find the answer you&apos;re looking for? Our support team is here to help you get the most out of NextCareer AI.
            </p>
            <a 
              href="mailto:support@NextCareer AI" 
              className="btn-primary inline-flex"
            >
              Contact Support
            </a>
          </div>
        </motion.div>
      </div>
    </div>
  );
}
